#!/usr/bin/env python

import sys
import rospy
import rosbag

if len(sys.argv) != 4:
    print('usage: %s <input.bag> <output.bag> <seconds>' % sys.argv[0])
    sys.exit(1)

in_f = sys.argv[1]
out_f = sys.argv[2]
shift = int(sys.argv[3])

print('opening input bag %s...' % in_f)
in_bag = rosbag.Bag(in_f)

print('opening output bag %s...' % out_f)
out_bag = rosbag.Bag(out_f, 'w')

print('shifting time by %d seconds' % shift)
shift = rospy.rostime.Duration(shift, 0)
for topic, msg, t in in_bag.read_messages():
    if msg._has_header:
        msg.header.stamp += shift
    if topic == '/tf':
        for transform in msg.transforms:
            transform.header.stamp += shift
    out_bag.write(topic, msg, t + shift)

print('finished')
in_bag.close()
out_bag.close()

